import marimo

__generated_with = "0.24.0"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def _():
    from pathlib import Path

    import marimo as mo
    import numpy as np
    import pandas as pd
    import plotly.graph_objects as go
    from numpy.lib.stride_tricks import sliding_window_view as swv
    from plotly.subplots import make_subplots

    from i4b_bench.corpus import prepare_disturbances
    from i4b.gym_interface import BUILDING_NAMES2CLASS
    from i4b.gym_interface.room_env import RoomHeatEnv
from i4b_bench_data import aprbs

    return (
        BUILDING_NAMES2CLASS,
        Path,
        RoomHeatEnv,
        aprbs,
        go,
        make_subplots,
        mo,
        np,
        pd,
        prepare_disturbances,
        swv,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Multi-step FIR regression with quantile homotopy

    This notebook ports Sébastien's `TrainMLModel_Desired_to_Indoor_Homotopy.py`
    algorithm onto the **standard I4B environment** (`RoomHeatEnv`). Instead of the
    measured Oslo heat-pump data (`DataRegression.pkl`), the regression data are
    generated by driving the I4B building model with an excited **desired supply
    temperature** signal. The identified model is a multi-step-ahead finite impulse
    response (FIR) predictor of the indoor temperature, trained by:

    1. an exact, causality-masked least-squares solve (reference),
    2. the original gradient-descent scheme from Sébastien's script,
    3. asymmetric pinball-loss (quantile) models obtained by **homotopy** on the
       error weights, warm-started from the L2 solution.

    All equations are written out below; the implementation is vectorized with
    NumPy (each epoch is one dense matrix product per kernel) but is
    mathematically identical to the reference script.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Signal mapping: Oslo heat pump → I4B standard env

    | Sébastien channel | Meaning | I4B source | Role in regression |
    |---|---|---|---|
    | `Indoor` | Room temperature °C | `obs[0]` (`T_room`) | Target & past input |
    | `Supply` | HP supply temperature °C | `info["u"]` (applied setpoint) | Past input |
    | `Return` | HP return temperature °C | `obs[2]` (`T_hp_ret`) | Past input |
    | `Outdoor` | Ambient temperature °C | `T_amb` disturbance | Future input |
    | `Desired` | Requested supply setpoint °C | commanded setpoint | Future input (feature) |
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Model and loss

    Sampling step $\Delta t = 15$ min, memory depth $D$ (6 h) and prediction
    horizon $H$ (24 h). At each prediction origin $k$ the model predicts the
    **deviation** of the indoor temperature from its current value:

    $$\hat{y}_{k,h} \;=\; \widehat{T}_{in}[k+h] - T_{in}[k]
    \;=\; \sum_{f \in \mathcal{F}} \phi_{f,h}^\top\, u_f[k {-} D : k {+} H]
    \;+\; \sum_{p \in \mathcal{P}} \phi_{p,h}^\top\, x_p[k {-} D : k],$$

    for leads $h = 1,\dots,H$, future inputs
    $\mathcal{F} = \{$Outdoor, Desired$\}$ with kernels
    $\Phi_f \in \mathbb{R}^{H \times (D+H)}$, and past inputs
    $\mathcal{P} = \{$Indoor, Supply, Return$\}$ with kernels
    $\Phi_p \in \mathbb{R}^{H \times (D+1)}$.

    **Causality.** At lead $h$ only information available up to $k+h-1$ may be
    used, so future kernels are projected onto the mask

    $$M_{h,j} = \mathbb{1}\{j \le h + D - 1\}, \qquad \Phi_f \leftarrow \Phi_f \odot M.$$

    **Loss.** With per-window error $e_{k,h} = \hat{y}_{k,h} - y_{k,h}$,
    forgetting factor $\gamma$ per day of age, and weights $(w_+, w_-)$,

    $$J_{\mathrm{QR}} = \frac{1}{H\sum_k \gamma^{\tau_k}} \sum_{k,h}
    \gamma^{\tau_k}\big( w_+\, e_{k,h}^+ + w_-\,e_{k,h}^- \big),
    \qquad e^+ = \max(e,0),\; e^-=\max(-e,0),$$

    $$J_{\mathrm{L2}} = \frac{1}{H\sum_k \gamma^{\tau_k}}\sum_{k,h}
    \gamma^{\tau_k}\, \tfrac{1}{2} e_{k,h}^2,$$

    $$J = (1-\lambda)\, J_{\mathrm{QR}} + \lambda\, J_{\mathrm{L2}},
    \qquad \lambda \in [0,1].$$

    The pinball loss with $(w_+,w_-) = (1-\tau,\tau)$ is minimized by the
    $\tau$-quantile of the target distribution, which gives prediction bands.

    **Exact L2 solution.** For $\lambda = 1$ and uniform $\gamma$, the optimum
    per lead $h$ is a least-squares problem over the causally allowed columns,
    solved with the normal equations as a reference for the iterative schemes.

    **Homotopy (QR).** The asymmetric absolute loss has a kink at zero; the
    weights are annealed from a warm start toward the targets,

    $$\omega_\pm^{(t+1)} = \tfrac{1}{2}\,\omega_\pm^{(t)} + \tfrac{1}{2}\,w_\pm^{*},$$

    until $\lvert \omega_+ - w_+^{*} \rvert + \lvert \omega_- - w_-^{*} \rvert
    < 2\cdot10^{-3}$, as in the reference script.
    """)
    return


@app.cell
def _(BUILDING_NAMES2CLASS, Path, mo):
    repo = Path(__file__).resolve().parents[1]
    weather_files = sorted(
        p.name
        for p in (repo / "source-data/normalized/weather_reference").glob(
            "de_freiburg_*.parquet"
        )
    )
    building_ui = mo.ui.dropdown(
        list(BUILDING_NAMES2CLASS), value="sfh_1969_1978_0_soc", label="Building"
    )
    weather_ui = mo.ui.dropdown(
        weather_files, value="de_freiburg_period_a.parquet", label="Weather file"
    )
    amplitude_ui = mo.ui.slider(
        0.0, 6.0, 0.5, value=4.0, label="APRBS residual amplitude (°C)"
    )
    hold_ui = mo.ui.range_slider(
        1, 96, 1, value=(4, 24), show_value=True, label="APRBS hold range (steps)"
    )
    start_ui = mo.ui.text(value="2024-11-01", label="Start")
    stop_ui = mo.ui.text(value="2025-01-15", label="Stop")
    mo.vstack(
        [
            mo.md("## 1. Generate regression data in the standard env"),
            mo.md(
                "The desired supply temperature is a heating-curve base "
                "$T_{des} = \\mathrm{clip}(26 + 0.9(4 - T_{amb}), 22, 45)$°C plus an "
                "APRBS residual, clipped to the env action range. Two warm-up days "
                "run at the base curve before recording starts."
            ),
            mo.hstack(
                [building_ui, weather_ui, amplitude_ui, hold_ui, start_ui, stop_ui]
            ),
        ]
    )
    return (
        amplitude_ui,
        building_ui,
        hold_ui,
        repo,
        start_ui,
        stop_ui,
        weather_ui,
    )


@app.cell
def _(
    BUILDING_NAMES2CLASS,
    RoomHeatEnv,
    amplitude_ui,
    aprbs,
    building_ui,
    hold_ui,
    np,
    pd,
    prepare_disturbances,
    repo,
    start_ui,
    stop_ui,
    weather_ui,
):
    import time

    _name = building_ui.value
    _params = dict(BUILDING_NAMES2CLASS[_name])
    _weather = pd.read_parquet(
        repo / "source-data/normalized/weather_reference" / weather_ui.value
    )
    _disturb = prepare_disturbances(
        _weather,
        _params,
        repo / "i4b_data/profiles/InternalGains/ResidentialDetached.csv",
    ).loc[start_ui.value : stop_ui.value]

    _env = RoomHeatEnv(
        hp_model="Heatpump_AW",
        building=_name,
        method="4R3C",
        mdot_HP=float(_params["mdot_hp"]),
        internal_gain_profile="unused",
        backend="legacy",
        disturbances=_disturb,
    )
    _T_amb = _disturb["T_amb"].to_numpy()
    _base = np.clip(26 + 0.9 * (4 - _T_amb), 22, 45)
    _hold_lo, _hold_hi = hold_ui.value
    _wave = aprbs(
        _disturb.index,
        f"homotopy-{_name}",
        low=-1.0,
        high=1.0,
        min_hold_steps=int(_hold_lo),
        max_hold_steps=max(int(_hold_lo), int(_hold_hi)),
    ).to_numpy()
    _desired = np.clip(_base + float(amplitude_ui.value) * _wave, 5, 65)

    _n = len(_disturb) - 1
    _rec = np.empty((_n, 5), dtype=np.float32)
    _obs = _env.get_obs()
    _warm = 2 * 24 * 4
    _t0 = time.time()
    for _k in range(_n):
        _target = float(np.clip(_base[_k], 5, 65) if _k < _warm else _desired[_k])
        _obs, _, _, _, _info = _env.step(_env.normalize_action(_target))
        _rec[_k] = (_obs[0], _info["u"], _obs[2], _T_amb[_k], _target)
    sim_seconds = time.time() - _t0

    data = pd.DataFrame(
        {
            "Time": _disturb.index[:_n],
            "Indoor": _rec[:, 0],
            "Supply": _rec[:, 1],
            "Return": _rec[:, 2],
            "Outdoor": _rec[:, 3],
            "Desired": _rec[:, 4],
        }
    )
    return data, sim_seconds


@app.cell
def _(data, go, make_subplots, mo, sim_seconds):
    _fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Temperatures (°C)", "Ambient excitation (°C)"),
    )
    for _label, _color in [
        ("Indoor", "green"),
        ("Supply", "red"),
        ("Return", "darkred"),
        ("Desired", "magenta"),
    ]:
        _fig.add_trace(
            go.Scatter(
                x=data["Time"],
                y=data[_label],
                name=_label,
                line=dict(color=_color, width=1),
            ),
            row=1,
            col=1,
        )
    _fig.add_trace(
        go.Scatter(
            x=data["Time"],
            y=data["Outdoor"],
            name="Outdoor",
            line=dict(color="royalblue", width=1),
        ),
        row=2,
        col=1,
    )
    _fig.update_layout(height=480, margin=dict(t=40, b=30, l=10, r=10))
    mo.md(
        f"Simulated `{len(data)}` steps in `{sim_seconds:.1f} s`. "
        f"{mo.as_html(_fig)}"
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## 2. Windowed regression assembly

    Prediction origins run over all $k$ with $D \le k \le N - H - 1$. Windows
    are built zero-copy with `sliding_window_view`; the tail is split
    chronologically for validation.
    """)
    return


@app.cell
def _(data, mo, np, swv):
    _values = data[["Indoor", "Supply", "Return", "Outdoor", "Desired"]].to_numpy()
    DT_MIN = 15
    DEPTH = int(6 * 60 / DT_MIN)
    HORIZON = int(24 * 60 / DT_MIN)
    _m = len(_values)
    _idx = np.arange(DEPTH, _m - HORIZON)
    n_windows = len(_idx)
    target = swv(_values[:, 0], HORIZON + 1)[_idx][:, 1:] - _values[_idx, 0][:, None]
    _columns = {"Indoor": 0, "Supply": 1, "Return": 2, "Outdoor": 3, "Desired": 4}
    FUTURE = ["Outdoor", "Desired"]
    PAST = ["Indoor", "Supply", "Return"]
    windows_future = {
        _v: swv(_values[:, _columns[_v]], DEPTH + HORIZON)[_idx - DEPTH]
        for _v in FUTURE
    }
    windows_past = {
        _v: swv(_values[:, _columns[_v]], DEPTH + 1)[_idx - DEPTH] for _v in PAST
    }
    causal_mask = np.tril(
        np.ones((HORIZON, DEPTH + HORIZON), dtype=np.float32), k=DEPTH - 1
    )
    split_ui = mo.ui.slider(
        0.5, 0.9, 0.05, value=0.75, label="Train fraction (chronological)"
    )
    mo.vstack(
        [
            mo.md(
                f"`D={DEPTH}` steps depth, `H={HORIZON}` steps horizon, "
                f"`{n_windows}` prediction windows."
            ),
            split_ui,
        ]
    )
    return (
        DEPTH,
        DT_MIN,
        FUTURE,
        HORIZON,
        PAST,
        causal_mask,
        split_ui,
        target,
        windows_future,
        windows_past,
    )


@app.cell
def _(FUTURE, PAST, np, split_ui, windows_future, windows_past):
    n_all = len(windows_future[FUTURE[0]])
    n_train = int(n_all * split_ui.value)
    train_slice = slice(0, n_train)
    val_slice = slice(n_train, n_all)
    x_future_concat = np.concatenate(
        [windows_future[_v] for _v in FUTURE], axis=1
    )
    x_past_concat = np.concatenate([windows_past[_v] for _v in PAST], axis=1)
    return train_slice, val_slice, x_future_concat, x_past_concat


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## 3. Exact causality-masked L2 solution

    Per lead $h$ the quadratic loss is minimized in closed form

    $$\theta_h^\star = (A_h^\top A_h)^{-1} A_h^\top y_h,\qquad
    A_h = \big[\,U_{\mathrm{fut}}[:, \mathrm{causal}(h)]\;\; U_{\mathrm{past}}\,\big],$$

    row-by-row over the training windows. This runs in a few seconds and gives
    the optimum that the iterative schemes below should approach.
    """)
    return


@app.cell
def _(
    DEPTH,
    FUTURE,
    HORIZON,
    PAST,
    np,
    target,
    train_slice,
    x_future_concat,
    x_past_concat,
):
    import time as _time

    _fw = DEPTH + HORIZON
    _pw = DEPTH + 1
    _t0 = _time.time()
    phi_l2 = {
        "Future": {_v: np.zeros((HORIZON, _fw)) for _v in FUTURE},
        "Past": {_v: np.zeros((HORIZON, _pw)) for _v in PAST},
    }
    for _i in range(HORIZON):
        _width = _i + DEPTH
        _cols = np.concatenate(
            [_q * _fw + np.arange(_width) for _q in range(len(FUTURE))]
        )
        _A = np.concatenate(
            [x_future_concat[train_slice, _cols], x_past_concat[train_slice]],
            axis=1,
        )
        _coef, _, _, _ = np.linalg.lstsq(_A, target[train_slice, _i], rcond=None)
        _off = 0
        for _q, _v in enumerate(FUTURE):
            phi_l2["Future"][_v][_i, :_width] = _coef[_off : _off + _width]
            _off += _width
        _off = len(FUTURE) * _width
        for _q, _v in enumerate(PAST):
            phi_l2["Past"][_v][_i] = _coef[_off + _q * _pw : _off + (_q + 1) * _pw]
    l2_solve_seconds = _time.time() - _t0
    return l2_solve_seconds, phi_l2


@app.cell
def _(FUTURE, PAST, np, windows_future, windows_past):
    def predict(phi, sel):
        _p = sum(
            np.einsum("hw,nw->nh", phi["Future"][_v], windows_future[_v][sel])
            for _v in FUTURE
        )
        _p += sum(
            np.einsum("hw,nw->nh", phi["Past"][_v], windows_past[_v][sel])
            for _v in PAST
        )
        return _p

    return (predict,)


@app.cell
def _(
    DT_MIN,
    HORIZON,
    go,
    l2_solve_seconds,
    mo,
    np,
    pd,
    phi_l2,
    predict,
    target,
    train_slice,
    val_slice,
):
    _leads_h = [1, 3, 6, 12, 24]
    _rows = []
    for _sel, _split in ((train_slice, "train"), (val_slice, "validation")):
        _err = predict(phi_l2, _sel) - target[_sel]
        _rmse = np.sqrt((_err**2).mean(axis=0))
        _pers = np.sqrt((target[_sel] ** 2).mean(axis=0))
        for _h in _leads_h:
            _s = int(_h * 60 / DT_MIN) - 1
            _rows.append(
                {
                    "split": _split,
                    "lead_h": _h,
                    "FIR RMSE [K]": round(float(_rmse[_s]), 3),
                    "persistence RMSE [K]": round(float(_pers[_s]), 3),
                }
            )
    rmse_table = pd.DataFrame(_rows)

    _err_val = predict(phi_l2, val_slice) - target[val_slice]
    _pers_val = target[val_slice]
    _lead_grid = np.arange(1, HORIZON + 1) * DT_MIN / 60.0
    _fig = go.Figure()
    _fig.add_trace(
        go.Scatter(
            x=_lead_grid,
            y=np.sqrt((_err_val**2).mean(axis=0)),
            name="exact masked L2",
            line=dict(color="darkred"),
        )
    )
    _fig.add_trace(
        go.Scatter(
            x=_lead_grid,
            y=np.sqrt((_pers_val**2).mean(axis=0)),
            name="persistence",
            line=dict(color="gray", dash="dash"),
        )
    )
    _fig.update_layout(
        height=360,
        margin=dict(t=30, b=30, l=10, r=10),
        xaxis_title="lead (h)",
        yaxis_title="validation RMSE (K)",
    )
    mo.vstack(
        [
            mo.md(f"Exact solve time: `{l2_solve_seconds:.1f} s`."),
            mo.ui.table(rmse_table, pagination=False, selection=None),
            mo.as_html(_fig),
        ]
    )
    return


@app.cell
def _(DEPTH, DT_MIN, FUTURE, HORIZON, PAST, go, make_subplots, mo, np, phi_l2):
    _names = FUTURE + PAST
    _fig = make_subplots(
        rows=1,
        cols=len(_names),
        subplot_titles=[f"Phi_{n}" for n in _names],
        horizontal_spacing=0.06,
    )
    for _c, _v in enumerate(_names, start=1):
        _kind = "Future" if _v in FUTURE else "Past"
        _w = phi_l2[_kind][_v].shape[1]
        _x = (-DEPTH + np.arange(_w)) * DT_MIN / 60.0
        _fig.add_trace(
            go.Heatmap(
                z=phi_l2[_kind][_v],
                x=_x,
                y=np.arange(1, HORIZON + 1) * DT_MIN / 60.0,
                colorscale="RdBu_r",
                zmid=0,
                showscale=_c == len(_names),
            ),
            row=1,
            col=_c,
        )
    _fig.update_layout(height=340, margin=dict(t=40, b=30, l=10, r=10))
    _fig.update_xaxes(title_text="lag relative to prediction origin (h)")
    _fig.update_yaxes(title_text="lead (h)", row=1, col=1)
    mo.vstack(
        [
            mo.md(
                "### Learned kernels (exact L2). Future kernels vanish above the "
                "causality line at lag = lead; past kernels show the indoor "
                "temperature's own autoregressive structure."
            ),
            mo.as_html(_fig),
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## 4. Gradient descent (reference-script dynamics)

    Same loss, causal projection and adaptive step size as Sébastien's script:

    $$\Phi^{(t+1)} = \big(\Phi^{(t)} - \alpha \nabla_\Phi J\big)\odot M,$$

    with $\alpha$ halved whenever the loss increases. Press the button to run
    gradient descent from zero kernels and compare with the exact solution.
    """)
    return


@app.cell
def _(mo):
    gd_alpha_ui = mo.ui.slider(
        -4.0, -1.0, 0.25, value=-2.0, label="log₁₀ initial step size α"
    )
    gd_iters_ui = mo.ui.slider(50, 1000, 50, value=250, label="Iterations")
    gd_button = mo.ui.run_button(label="Run gradient descent")
    mo.hstack([gd_alpha_ui, gd_iters_ui, gd_button])
    return gd_alpha_ui, gd_button, gd_iters_ui


@app.cell
def _(
    DEPTH,
    FUTURE,
    HORIZON,
    PAST,
    causal_mask,
    gd_alpha_ui,
    gd_button,
    gd_iters_ui,
    np,
    target,
    train_slice,
    windows_future,
    windows_past,
):
    if gd_button.value:
        import time as _t

        _t0 = _t.time()
        _n = train_slice.stop - train_slice.start
        _g = np.ones(_n)
        _sc = 1 / (_g.sum() * HORIZON)
        _phi = {
            "Future": {
                _v: np.zeros((HORIZON, DEPTH + HORIZON)) for _v in FUTURE
            },
            "Past": {_v: np.zeros((HORIZON, DEPTH + 1)) for _v in PAST},
        }
        _alpha = 10.0 ** gd_alpha_ui.value
        losses_gd = []
        _prev = np.inf
        for _it in range(int(gd_iters_ui.value)):
            _pred = sum(
                np.einsum(
                    "hw,nw->nh",
                    _phi["Future"][_v],
                    windows_future[_v][train_slice],
                )
                for _v in FUTURE
            )
            _pred += sum(
                np.einsum(
                    "hw,nw->nh", _phi["Past"][_v], windows_past[_v][train_slice]
                )
                for _v in PAST
            )
            _err = _pred - target[train_slice]
            _loss = float(0.5 * (_g[:, None] * _err**2).sum() * _sc)
            losses_gd.append(_loss)
            if _loss > _prev:
                _alpha *= 0.5
            _prev = _loss
            for _v in FUTURE:
                _phi["Future"][_v] -= (
                    _alpha
                    * np.einsum(
                        "nh,n,nw->hw", _err, _g, windows_future[_v][train_slice]
                    )
                    * _sc
                )
                _phi["Future"][_v] *= causal_mask
            for _v in PAST:
                _phi["Past"][_v] -= (
                    _alpha
                    * np.einsum(
                        "nh,n,nw->hw", _err, _g, windows_past[_v][train_slice]
                    )
                    * _sc
                )
        _sec = _t.time() - _t0
        phi_gd = _phi
        gd_status = f"finished in {_sec:.0f} s"
    else:
        phi_gd, losses_gd, gd_status = None, [], "not run"
    return gd_status, losses_gd, phi_gd


@app.cell
def _(
    DT_MIN,
    gd_status,
    go,
    losses_gd,
    mo,
    np,
    pd,
    phi_gd,
    phi_l2,
    predict,
    target,
    train_slice,
    val_slice,
):
    if phi_gd is None:
        gd_display = mo.md(
            f"Gradient descent {gd_status}. Press the button above to train."
        )
    else:
        _fig = go.Figure()
        _fig.add_trace(
            go.Scatter(
                x=np.arange(len(losses_gd)),
                y=losses_gd,
                name="gradient descent",
                line=dict(color="steelblue"),
            )
        )
        _err_exact = predict(phi_l2, train_slice) - target[train_slice]
        _exact_loss = 0.5 * float((_err_exact**2).mean())
        _fig.add_hline(
            y=_exact_loss,
            line=dict(color="darkred", dash="dash"),
            annotation_text="exact L2 optimum",
        )
        _fig.update_layout(
            height=320,
            margin=dict(t=30, b=30, l=10, r=10),
            yaxis_type="log",
            xaxis_title="iteration",
            yaxis_title="training loss",
        )

        _rows = []
        for _sel, _split in ((train_slice, "train"), (val_slice, "validation")):
            for _tag, _phi in (("exact L2", phi_l2), ("gradient descent", phi_gd)):
                _e = predict(_phi, _sel) - target[_sel]
                _rmse = np.sqrt((_e**2).mean(axis=0))
                for _h in (1, 6, 24):
                    _s = int(_h * 60 / DT_MIN) - 1
                    _rows.append(
                        {
                            "split": _split,
                            "model": _tag,
                            "lead_h": _h,
                            "RMSE [K]": round(float(_rmse[_s]), 3),
                        }
                    )
        gd_display = mo.vstack(
            [
                mo.as_html(_fig),
                mo.ui.table(
                    pd.DataFrame(_rows), pagination=False, selection=None
                ),
            ]
        )
    gd_display
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## 5. Quantile homotopy (asymmetric pinball loss)

    Training with $(w_+, w_-)=(1-\tau,\tau)$ and $\lambda=0$ yields the
    $\tau$-quantile of $\Delta T_{in}$ at every lead. As in the reference
    script, models are **warm-started from the L2 solution** and the weights
    anneal toward the quantile targets, starting from $(0.2,0.8)$ for upper
    and $(0.8,0.2)$ for lower quantiles — a smooth path through a non-smooth
    objective.
    """)
    return


@app.cell
def _(mo):
    tau_ui = mo.ui.slider(
        0.5, 0.99, 0.01, value=0.95, label="Upper quantile τ (lower = 1−τ)"
    )
    qr_iters_ui = mo.ui.slider(
        50, 800, 50, value=200, label="Iterations per quantile model"
    )
    qr_button = mo.ui.run_button(label="Run quantile homotopy (2 models)")
    mo.hstack([tau_ui, qr_iters_ui, qr_button])
    return qr_button, qr_iters_ui, tau_ui


@app.cell
def _(
    FUTURE,
    HORIZON,
    PAST,
    causal_mask,
    np,
    phi_l2,
    qr_button,
    qr_iters_ui,
    target,
    tau_ui,
    train_slice,
    windows_future,
    windows_past,
):
    def _train_quantile(tau, iters, alpha0=1e-3):
        _phi = {
            "Future": {_v: phi_l2["Future"][_v].copy() for _v in FUTURE},
            "Past": {_v: phi_l2["Past"][_v].copy() for _v in PAST},
        }
        _n = train_slice.stop - train_slice.start
        _g = np.ones(_n)
        _sc = 1 / (_g.sum() * HORIZON)
        _target_w = (1.0 - tau, tau)
        _w = [0.2, 0.8] if tau > 0.5 else [0.8, 0.2]
        _logs = []
        _weights = [tuple(_w)]
        _alpha = alpha0
        _prev = np.inf
        for _it in range(iters):
            _pred = sum(
                np.einsum(
                    "hw,nw->nh",
                    _phi["Future"][_v],
                    windows_future[_v][train_slice],
                )
                for _v in FUTURE
            )
            _pred += sum(
                np.einsum(
                    "hw,nw->nh", _phi["Past"][_v], windows_past[_v][train_slice]
                )
                for _v in PAST
            )
            _err = _pred - target[train_slice]
            _loss = float(
                (_g[:, None] * (_w[0] * _err * (_err > 0)
                                - _w[1] * _err * (_err < 0))).sum() * _sc
            )
            _logs.append(_loss)
            if _loss > _prev:
                _alpha *= 0.5
            _prev = _loss
            _signs = _w[0] * (_err > 0) - _w[1] * (_err < 0)
            for _v in FUTURE:
                _phi["Future"][_v] -= (
                    _alpha
                    * np.einsum(
                        "nh,n,nw->hw", _signs, _g, windows_future[_v][train_slice]
                    )
                    * _sc
                )
                _phi["Future"][_v] *= causal_mask
            for _v in PAST:
                _phi["Past"][_v] -= (
                    _alpha
                    * np.einsum(
                        "nh,n,nw->hw", _signs, _g, windows_past[_v][train_slice]
                    )
                    * _sc
                )
            if _it % 20 == 19 and (
                abs(_w[0] - _target_w[0]) + abs(_w[1] - _target_w[1]) > 2e-3
            ):
                _w[0] = 0.5 * _w[0] + 0.5 * _target_w[0]
                _w[1] = 0.5 * _w[1] + 0.5 * _target_w[1]
                _weights.append(tuple(_w))
        return _phi, _logs, _weights

    if qr_button.value:
        import time as _t

        _tau_hi = float(tau_ui.value)
        _iters = int(qr_iters_ui.value)
        _t0 = _t.time()
        phi_lo, qr_log_lo, qr_w_lo = _train_quantile(1.0 - _tau_hi, _iters)
        phi_hi, qr_log_hi, qr_w_hi = _train_quantile(_tau_hi, _iters)
        qr_status = f"finished in {_t.time() - _t0:.0f} s"
    else:
        phi_lo = phi_hi = None
        qr_log_lo = qr_log_hi = qr_w_lo = qr_w_hi = []
        qr_status = "not run"
    return phi_hi, phi_lo, qr_log_hi, qr_log_lo, qr_status, qr_w_hi, qr_w_lo


@app.cell
def _(
    DT_MIN,
    HORIZON,
    go,
    mo,
    np,
    phi_hi,
    phi_lo,
    predict,
    qr_log_hi,
    qr_log_lo,
    qr_status,
    qr_w_hi,
    qr_w_lo,
    target,
    tau_ui,
    val_slice,
):
    if phi_lo is None:
        cov_lo = cov_hi = cov_band = None
        qr_display = mo.md(
            f"Quantile homotopy {qr_status}. Press the button above to train."
        )
    else:
        _y_val = target[val_slice]
        _p_lo = predict(phi_lo, val_slice)
        _p_hi = predict(phi_hi, val_slice)
        cov_lo = float((_y_val < _p_lo).mean())
        cov_hi = float((_y_val < _p_hi).mean())
        cov_band = float(((_y_val >= _p_lo) & (_y_val <= _p_hi)).mean())

        _lead_grid = np.arange(1, HORIZON + 1) * DT_MIN / 60.0
        _fig_cov = go.Figure()
        _fig_cov.add_trace(
            go.Scatter(
                x=_lead_grid,
                y=(_y_val < _p_lo).mean(axis=0),
                name="lower model",
            )
        )
        _fig_cov.add_trace(
            go.Scatter(
                x=_lead_grid,
                y=(_y_val < _p_hi).mean(axis=0),
                name="upper model",
            )
        )
        _fig_cov.add_hline(y=1 - tau_ui.value, line_dash="dash", line_color="gray")
        _fig_cov.add_hline(y=tau_ui.value, line_dash="dash", line_color="gray")
        _fig_cov.update_layout(
            height=280,
            margin=dict(t=30, b=30, l=10, r=10),
            xaxis_title="lead (h)",
            yaxis_title="empirical P(y < ŷ)",
        )

        _fig_loss = go.Figure()
        _fig_loss.add_trace(
            go.Scatter(
                x=np.arange(len(qr_log_lo)),
                y=qr_log_lo,
                name="lower pinball loss",
            )
        )
        _fig_loss.add_trace(
            go.Scatter(
                x=np.arange(len(qr_log_hi)),
                y=qr_log_hi,
                name="upper pinball loss",
            )
        )
        _fig_loss.update_layout(
            height=260,
            margin=dict(t=30, b=30, l=10, r=10),
            yaxis_type="log",
            xaxis_title="iteration",
            yaxis_title="pinball loss",
        )

        _w_arr_lo = np.array(qr_w_lo)
        _w_arr_hi = np.array(qr_w_hi)

        qr_display = mo.vstack(
            [
                mo.md(
                    f"Coverage at nominal quantiles: lower model `{cov_lo:.3f}` "
                    f"(target `{1 - tau_ui.value:.2f}`), upper model "
                    f"`{cov_hi:.3f}` (target `{tau_ui.value:.2f}`), joint band "
                    f"`{cov_band:.3f}`. Homotopy reached "
                    f"`w± = {qr_w_hi[-1]}` (upper) and `{qr_w_lo[-1]}` (lower) "
                    f"through {len(qr_w_hi)} weight updates."
                ),
                mo.as_html(_fig_cov),
                mo.as_html(_fig_loss),
            ]
        )
    qr_display
    return


@app.cell
def _(mo, phi_lo, val_slice):
    if phi_lo is None:
        day_ui = None
        band_intro = mo.md("")
    else:
        _n_val = val_slice.stop - val_slice.start
        day_ui = mo.ui.slider(
            0,
            max(0, _n_val - 2),
            1,
            value=max(0, _n_val // 2),
            label="Validation window index",
        )
        band_intro = mo.md(
            f"### Quantile band on one validation window {day_ui}"
        )
    band_intro
    return (day_ui,)


@app.cell
def _(
    DEPTH,
    HORIZON,
    data,
    day_ui,
    go,
    mo,
    phi_hi,
    phi_l2,
    phi_lo,
    predict,
    val_slice,
):
    if phi_lo is None or day_ui is None:
        band_display = mo.md("")
    else:
        _k = int(day_ui.value) + val_slice.start
        _t0 = DEPTH + _k
        _times = data["Time"].iloc[_t0 : _t0 + HORIZON + 1]
        _T_now = data["Indoor"].iloc[_t0]
        _actual = data["Indoor"].iloc[_t0 : _t0 + HORIZON + 1]
        _sel = slice(_k, _k + 1)
        _med = _T_now + predict(phi_l2, _sel)[0]
        _lo = _T_now + predict(phi_lo, _sel)[0]
        _hi = _T_now + predict(phi_hi, _sel)[0]

        _fig = go.Figure()
        _fig.add_trace(
            go.Scatter(
                x=list(_times[1:]) + list(_times[1:][::-1]),
                y=list(_hi) + list(_lo[::-1]),
                fill="toself",
                fillcolor="rgba(70,130,180,0.25)",
                line=dict(color="rgba(70,130,180,0.0)"),
                name="quantile band",
            )
        )
        _fig.add_trace(
            go.Scatter(
                x=list(_times),
                y=list(_actual),
                name="realized Indoor",
                line=dict(color="green", width=2),
            )
        )
        _fig.add_trace(
            go.Scatter(
                x=list(_times[1:]),
                y=list(_med),
                name="L2 (conditional mean)",
                line=dict(color="darkred"),
            )
        )
        _fig.update_layout(
            height=380,
            margin=dict(t=30, b=30, l=10, r=10),
            xaxis_title="time",
            yaxis_title="Indoor (°C)",
        )
        band_display = mo.as_html(_fig)
    band_display
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Summary

    - The masked multi-step FIR predictor clearly outperforms persistence on
      the standard I4B building; the exact L2 solution is available in closed
      form per lead and serves as convergence reference.
    - Sébastien's gradient descent with adaptive step size converges toward
      the same optimum, but slowly for these highly correlated windows (his
      script therefore runs for very many iterations with an exit threshold).
    - The asymmetric pinball loss, warm-started from L2 and annealed by the
      weight homotopy, produces calibrated quantile models: empirical coverage
      tracks the nominal $\tau$ across the 24 h lead.
    - The original script persists `Phi<Tag>_<dt>_Desired_to_Indoor.pkl` plus
      `RegressionSetup.pkl`; the dictionary layout
      (`{'Future': {var: kernel}, 'Past': {var: kernel}}`) matches it exactly.
    """)
    return


if __name__ == "__main__":
    app.run()
